# Generated by Django 4.1.5 on 2023-01-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='id_course',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('email', 'course')},
        ),
    ]
